build:
  test:
    image: golang:1.5
    environment:
      - CGO_ENABLED=0
      - GO15VENDOREXPERIMENT=1
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER"

publish:
  coverage:
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/docker
    tag: latest
    when:
      branch: master

plugin:
  name: Docker
  desc: Build and publish images to a Docker registry
  type: publish
  image: plugins/docker
  labels:
    - docker
    - image
    - container
