workspace:
  base: /go

script:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER"
  docker:
    storage_driver: overlay
    repo: plugins/docker
    tag: latest
    when:
      branch: master
      event: push

plugin:
  name: Docker
  desc: Build and publish images to a Docker registry
  type: publish
  image: plugins/docker
  labels:
    - docker
    - image
    - container
